# .tekton/tasks.yml
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup-task
spec:
  steps:
    - name: cleanup
      image: alpine
      script: |
        #!/bin/sh
        echo "Cleanup task completed!"

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nose-test-task
spec:
  steps:
    - name: run-tests
      image: python:3.9
      script: |
        #!/bin/sh
        echo "Running tests..."
        python app.py
