# .tekton/tasks.yml
# This file defines Tekton tasks for the CI/CD pipeline

---
# Task 1: Cleanup Task
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup-task # Name of the task
spec:
  steps:
    # Step 1: Cleanup step
    - name: cleanup
      image: alpine # Lightweight image for shell scripts
      script: |
        #!/bin/sh
        echo "Performing cleanup..."
        rm -rf /tmp/*
        echo "Cleanup completed successfully!"

---
# Task 2: Build Task
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-task # Name of the task
spec:
  steps:
    # Step 1: Build step
    - name: build
      image: python:3.9
      script: |
        #!/bin/sh
        echo "Building application..."
        python -m compileall app.py
        echo "Build completed successfully!"

---
# Task 3: Nose Test Task
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nose-test-task # Name of the task
spec:
  steps:
    # Step 1: Run tests using Nose
    - name: run-nose-tests
      image: python:3.9
      script: |
        #!/bin/sh
        echo "Installing dependencies..."
        pip install --upgrade pip
        pip install nose
        echo "Running tests with Nose..."
        nosetests -v
