# .github/workflows/workflow.yml
name: CI Workflow

# Trigger this workflow on push or pull requests to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job for linting the code
  lint:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # Step 3: Install and run Flake8 linter
      - name: Install Flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Lint with Flake8
        run: flake8 .

  # Job for running unit tests
  test:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nose

      # Step 4: Run unit tests using Nose
      - name: Run unit tests with Nose
        run: |
          # Run Nose tests in verbose mode
          nosetests -v
